#!/bin/bash
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.

#
#	FUNCTIONS
#

function set_default_config {
	cat > ${BASE_PATH}/config <<EOF
# User agent
USER_AGENT="Mozilla/5.0 (Ubuntu; X11; Linux x86_64; rv:8.0) Gecko/20100101 Firefox/8.0"

# Desktop [GNOME2|GNOME3]
DESKTOP="GNOME3"

# Resolution 
# [320x240|320x400|320x480|360x480|480x272|480x800|600x1024|640x480|640x960|800x480|960x800|960x854|
# 1024x1024|1024x600|1024x768|1080x960|1280x1024|1280x720|1280x800|1280x960|1366x768|1400x1050|1440x900|
# 1600x1200|1600x900|1680x1050|1920x1080|1920x1200|2048x2048|2560x1440|2560x1600]
RESOLUTION="1920x1200"

# Keep old wallpaper
# [yes|no]
ARCHIVE="no"
EOF
}
function edit_config {
	gnome-text-editor "${BASE_PATH}/config"
	exit 0;
}
function get_wall_filename {
	wget -U "${USER_AGENT}" -q -O- ${FEED_URL} | grep -P -o 'http://*[^:]*\.jpg' | head -n1 | sed -e 's/previews/7yz4ma1/g' | sed -e 's/\.jpg/_'${RESOLUTION}'\.jpg/g'
}
function save_wall_filename {
	echo ${1} > ${LAST_WALL}
}
function get_last_filename {
	if [ -f ${LAST_WALL} ]
	then
		cat ${LAST_WALL}
	else
		echo "init" > ${LAST_WALL}
		cat ${LAST_WALL}
	fi
}
function download_wallpaper {
	
	if [ ${ARCHIVE} = "yes" ]
	then
		if [ ! -d ${BASE_PATH}/archive ]
		then
			mkdir -p ${BASE_PATH}/archive
		fi
		if [ -e ${BG_PATH} ]
		then
			cp ${BG_PATH} ${BASE_PATH}/archive/$(date +%s)-wallpaper.jpg
		fi
	fi

	wget -U "${USER_AGENT}" -q -O ${TMP_PATH} ${1}
	mv ${TMP_PATH} ${BG_PATH}
}

#
#	SCRIPT
#

FEED_URL="http://feeds.feedburner.com/InterfaceliftNewestWallpaper"
BASE_PATH="$HOME/.local/share/iflwallpaper"
BG_PATH="${BASE_PATH}/wallpaper.jpg"
TMP_PATH="${BASE_PATH}/wallpaper.tmp"
LAST_WALL="${BASE_PATH}/wallpaper.last"

if [ ! -d ${BASE_PATH} ]
then
	mkdir -p ${BASE_PATH}
	set_default_config
	edit_config
fi

source ${BASE_PATH}/config

if [ "$1" = "conf" ]
then
	edit_config
fi

NEW=$(get_wall_filename)

if [ ${NEW} != $(get_last_filename) ] 
then 
	download_wallpaper "${NEW}"
	save_wall_filename "${NEW}"
fi

case $DESKTOP in
	GNOME2)
		/usr/bin/gconftool-2 -t string -s /desktop/gnome/background/picture_filename ${BG_PATH}
	;;
	GNOME3)
		/usr/bin/gsettings set org.gnome.desktop.background picture-uri file://${BG_PATH}
	;;
esac
